# Generated by Django 3.0.4 on 2020-03-15 16:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=20)),
                ('chunk_id', models.CharField(max_length=20)),
                ('pid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('children', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
