# Generated by Django 3.0.4 on 2020-03-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Processes',
            new_name='Process',
        ),
    ]
