# Generated by Django 3.0.4 on 2020-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_process_isvalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='children',
        ),
        migrations.AddField(
            model_name='process',
            name='ppid',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
